<?php
$Repo = "CREATE TABLE IF NOT EXISTS repositories(
   idRepository INT NOT NULL AUTO_INCREMENT,
   RepositoryName VARCHAR(50) NOT NULL,
   RepositoryDescription TEXT NULL,
   RepositoryUser INT NOT NULL,
   CodRepository VARCHAR(50) NOT NULL,
   DateCreation DATE,
   PRIMARY KEY ( idRepository )
);";
mysqli_query($mysqli, $Repo) or die (mysql_error());
$RepoData = "CREATE TABLE IF NOT EXISTS repodata(
   id INT NOT NULL AUTO_INCREMENT,
   idUser INT NOT NULL,
   idRepository INT NOT NULL,
   Sequences VARCHAR(10) NOT NULL,
   Status VARCHAR(10) NOT NULL,
   Blasted VARCHAR(10) NOT NULL,
   Result VARCHAR(10) NOT NULL,
   Annotation VARCHAR(10) NOT NULL,
   NoResult VARCHAR(10) NOT NULL,
   PRIMARY KEY ( id )
);";
mysqli_query($mysqli, $RepoData) or die (mysql_error());
?>

<style type="text/css">
@keyframes ldio-5u9mvyjadya-1 {
    0% { transform: rotate(0deg) }
   50% { transform: rotate(-45deg) }
  100% { transform: rotate(0deg) }
}
@keyframes ldio-5u9mvyjadya-2 {
    0% { transform: rotate(180deg) }
   50% { transform: rotate(225deg) }
  100% { transform: rotate(180deg) }
}
.ldio-5u9mvyjadya > div:nth-child(2) {
  transform: translate(-15px,0);
}
.ldio-5u9mvyjadya > div:nth-child(2) div {
  position: absolute;
  top: 50px;
  left: 50px;
  width: 150px;
  height: 75px;
  border-radius: 150px 150px 0 0;
  background: #000000;
  animation: ldio-5u9mvyjadya-1 1s linear infinite;
  transform-origin: 75px 75px
}
.ldio-5u9mvyjadya > div:nth-child(2) div:nth-child(2) {
  animation: ldio-5u9mvyjadya-2 1s linear infinite
}
.ldio-5u9mvyjadya > div:nth-child(2) div:nth-child(3) {
  transform: rotate(-90deg);
  animation: none;
}@keyframes ldio-5u9mvyjadya-3 {
    0% { transform: translate(237.5px,0); opacity: 0 }
   20% { opacity: 1 }
  100% { transform: translate(87.5px,0); opacity: 1 }
}
.ldio-5u9mvyjadya > div:nth-child(1) {
  display: block;
}
.ldio-5u9mvyjadya > div:nth-child(1) div {
  position: absolute;
  top: 115px;
  left: -10px;
  width: 20px;
  height: 20px;
  border-radius: 50%;
  background: #000000;
  animation: ldio-5u9mvyjadya-3 1s linear infinite
}
.ldio-5u9mvyjadya > div:nth-child(1) div:nth-child(1) { animation-delay: -0.67s }
.ldio-5u9mvyjadya > div:nth-child(1) div:nth-child(2) { animation-delay: -0.33s }
.ldio-5u9mvyjadya > div:nth-child(1) div:nth-child(3) { animation-delay: 0s }
.loadingio-spinner-bean-eater-d7ai1rnktyt {
  width: 250px;
  height: 250px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-5u9mvyjadya {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-5u9mvyjadya div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>


<div class="modal fade " id="Edit">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Are You Sure?</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        There is no way to undo this action
      </div>
      <div class="modal-footer">
        <a id="modal-btn-yes" class="btn btn-danger" >Yes</a>
        <button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
      </div>
</div>
  </div>
</div>


<div class="modal fade" tabindex="-1" id="LoadingRepositories">
<div class="modal-dialog modal-dialog-centered">
<div class="modal-content">
<div class="modal-header bg-dark text-white">
<div class="modal-title text-center h4">Loading Repositories</div>
</div>
<div class="modal-body text-center">		

<div class="loadingio-spinner-bean-eater-d7ai1rnktyt"><div class="ldio-5u9mvyjadya">
<div><div></div><div></div><div></div></div><div><div></div><div></div><div></div></div>
</div></div>
	
</div>
<div class="modal-footer bg-dark text-white text-left"><div class="h5">Please wait...</div></div>
</div>
</div>
</div>

<div class="w-75 mx-auto">
<div class="input-group mb-3 mt-3">
<span class="input-group-text">Term to search: </span>
<input name="RepositoryName" type="text" autofocus="autofocus" class="form-control form-control-lg w-50" id="RepositoryName" placeholder="" autocomplete="on">
<button id="btnLoadDatabase" class="btn btn-lg btn-primary" type="button" onClick="LoadDatabase();"><i class="fa-solid fa-magnifying-glass"></i> Search Repositories</button>
</div>
</div>

<?php
$query 		= ("SELECT * FROM repositories WHERE RepositoryUser = ".$_SESSION['idUser']." ORDER BY idRepository DESC");
$result 	= mysqli_query($mysqli, $query) or die (mysqli_error());
?>
<?php
if(mysqli_num_rows($result) == 0) {
$R = "NO";
?>
<div class="text-center h3 text-white mt-5 mb-5">You have not registered any repositories in sGOat.</div>
<div class="text-center h3 text-white mt-5 mb-5">The repositories are used to store your sequences.</div>
<div class="text-center h3 text-white mt-5 mb-5">To create a repository, click on the button below.</div>
<div class="text-center h3 text-white mt-5 mb-5"><a class="btn btn-lg btn-primary" href="index.php?p=NewRepository&Action=CDS" role="button"><i class="fas fa-2x mr-2 fa-plus"></i> Create a new Repository</a></div>
<?php
} else {
$R = "YES";
?>
<div id="Repositories"></div>
<?php } ?>

<script>
$(document).ready(function() {	
<?php 
if($R == "YES"){
?>
$('[data-toggle="tooltip"]').tooltip();
$('#btnLoadDatabase').click();
$("#RepositoryName" ).keyup(function() {
if($('#RepositoryName').val().length == 0) {
$('#btnLoadDatabase').click();
}});
<?php } ?>

});
function LoadDatabase(){
$('#LoadingRepositories').modal('show');
var Repository = document.getElementById("RepositoryName").value;
var xhr;
if (window.XMLHttpRequest) {
xhr = new XMLHttpRequest();
} else if (window.ActiveXObject) { // IE 8 and older
xhr = new ActiveXObject("Microsoft.XMLHTTP");
}
	
var data = "Repository=" + Repository;
xhr.open("POST", "RepositoriesSearch.php", true); 
xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");                  
xhr.send(data);
xhr.onreadystatechange = display_data;
	
function display_data() {
if (xhr.readyState == 4) {
if (xhr.status == 200) {
//alert(xhr.responseText);	   
document.getElementById("Repositories").innerHTML = xhr.responseText;
$('#LoadingRepositories').modal('hide');
      } else {
        alert('There was a problem with the request.');
      }
     }
	}
}
</script>

