<style type="text/css">
@keyframes ldio-5u9mvyjadya-1 {
    0% { transform: rotate(0deg) }
   50% { transform: rotate(-45deg) }
  100% { transform: rotate(0deg) }
}
@keyframes ldio-5u9mvyjadya-2 {
    0% { transform: rotate(180deg) }
   50% { transform: rotate(225deg) }
  100% { transform: rotate(180deg) }
}
.ldio-5u9mvyjadya > div:nth-child(2) {
  transform: translate(-15px,0);
}
.ldio-5u9mvyjadya > div:nth-child(2) div {
  position: absolute;
  top: 50px;
  left: 50px;
  width: 150px;
  height: 75px;
  border-radius: 150px 150px 0 0;
  background: #000000;
  animation: ldio-5u9mvyjadya-1 1s linear infinite;
  transform-origin: 75px 75px
}
.ldio-5u9mvyjadya > div:nth-child(2) div:nth-child(2) {
  animation: ldio-5u9mvyjadya-2 1s linear infinite
}
.ldio-5u9mvyjadya > div:nth-child(2) div:nth-child(3) {
  transform: rotate(-90deg);
  animation: none;
}@keyframes ldio-5u9mvyjadya-3 {
    0% { transform: translate(237.5px,0); opacity: 0 }
   20% { opacity: 1 }
  100% { transform: translate(87.5px,0); opacity: 1 }
}
.ldio-5u9mvyjadya > div:nth-child(1) {
  display: block;
}
.ldio-5u9mvyjadya > div:nth-child(1) div {
  position: absolute;
  top: 115px;
  left: -10px;
  width: 20px;
  height: 20px;
  border-radius: 50%;
  background: #000000;
  animation: ldio-5u9mvyjadya-3 1s linear infinite
}
.ldio-5u9mvyjadya > div:nth-child(1) div:nth-child(1) { animation-delay: -0.67s }
.ldio-5u9mvyjadya > div:nth-child(1) div:nth-child(2) { animation-delay: -0.33s }
.ldio-5u9mvyjadya > div:nth-child(1) div:nth-child(3) { animation-delay: 0s }
.loadingio-spinner-bean-eater-d7ai1rnktyt {
  width: 250px;
  height: 250px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-5u9mvyjadya {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-5u9mvyjadya div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>

<div class="modal fade" tabindex="-1" id="FormLoading">
<div class="modal-dialog modal-dialog-centered">
<div class="modal-content">
<div class="modal-header bg-dark text-white">
<div class="modal-title text-center h4">sGOat Login</div>
</div>
<div class="modal-body text-center">		

<div class="loadingio-spinner-bean-eater-d7ai1rnktyt"><div class="ldio-5u9mvyjadya">
<div><div></div><div></div><div></div></div><div><div></div><div></div><div></div></div>
</div></div>
	
</div>
<div class="modal-footer bg-dark text-white text-left"><div class="h5">Please wait...</div></div>
</div>
</div>
</div>

<canvas></canvas>
<div class="fixed-top mt-4 align-middle">
<img class="rounded mx-auto d-block mb-2" src="img/logo.png" alt="" width="150">
<div class="h3 text-center">sGOat</div>
<div class="h4 text-center"><b>S</b>oftware <b>G</b>ene <b>O</b>ntology <b>A</b>nnotation <b>T</b>ranscriptome</div>
<div class="card w-75 mx-auto border-0 rounded mt-2">
<div class="card-header text-center bg-dark align-middle h5">Login into Your sGOat Account</div>
<div class="card-body text-black bg-black">
<form id="FormLogin">	
<div class="form-floating mb-5 mt-5 w-75 mx-auto">
<input name="Email" type="email" autofocus="autofocus" required="required" class="form-control form-control-lg" id="Email" placeholder="luanrabelo@outlook.com" autocomplete="on">
<label for="FloatingEmail">Email address</label>
</div>
<div class="form-floating mb-5 mt-5 w-75 mx-auto">
<input name="Pass" type="password" required="required" class="form-control form-control-lg" id="Pass" placeholder="Password">
<label for="FloatingPassword">Password</label>
</div>

<div class="row row-cols-3 mx-auto">
<div class="col-4 d-flex justify-content-center"><div class="form-check form-switch">
  <input id="Assistance" class="form-check-input" type="checkbox" role="switch" checked>
  <label class="text-white form-check-label h5" for="flexSwitchCheckChecked">Keep me Sign In</label>
</div></div>
<div class="col-4 h5 text-center"><a class="btn btn-lg btn-block btn-warning" href="Login.php?p=Recover" role="button"><i class="fas fa-2x fa-ticket-alt"></i> Forget Password? Click here</a></div>	
<div class="col-4 h5 text-center"><a class="btn btn-lg btn-block btn-light" href="Login.php?p=NewUser" role="button"><i class="fas fa-2x fa-user-circle"></i> New User? Click here</a></div>
</div>
<div class="d-grid gap-2 col-6 mx-auto mt-5 mb-2"><button class="btn btn-lg btn-block btn-success">Login</button></div>	
</form>
</div>
<div class="card-footer bg-dark text-white text-center align-middle">
<div class="h6">sGOat: A New Web-Based Tool For Transcriptome Data Annotation and Post-Filtering Sequence Analysis in No-Model Organism</div>
<div class="h6">Developer: Luan Rabelo; Collaborators: Marcelo Vallinoto, Cristiana Maciel, Murilo Maciel, Davidson Sodré, Iracilda Sampaio;</div>
<div class="h6">version 1.0 | Last update 01/02/2022</div>
</div>
</div>
</div>
<script>
var canvas = document.querySelector('canvas'), ctx = canvas.getContext('2d');
canvas.width = window.innerWidth-10;
canvas.height = window.innerHeight-10;
var letters = 'ACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTG';
letters = letters.split('');
var fontSize = 40, columns = canvas.width / fontSize;
var drops = [];
for (var i = 0; i < columns; i++) {
  drops[i] = 1;
}
	
function draw() {
  ctx.fillStyle = 'rgba(0, 0, 0, .1)';
  ctx.fillRect(0, 0, canvas.width, canvas.height);
  for (var i = 0; i < drops.length; i++) {
    var text = letters[Math.floor(Math.random() * letters.length)];
    ctx.fillStyle = '#39ff14';
    ctx.fillText(text, i * fontSize, drops[i] * fontSize);
    drops[i]++;
    if (drops[i] * fontSize > canvas.height && Math.random() > .50) {
      drops[i] = 0;
    }
  }
}
setInterval(draw, 250);	
</script>

<script>
$(document).ready(function(){
$('#FormLogin').submit(function(){
$('#FormLoading').modal('show'); 
	
var Login 	=$('#Email').val();
var Pass 	=$('#Pass').val();
if($('#Assistance').is(":checked")){
var Assistance = "YES";
} else {
var Assistance = "NO";
}

$.ajax({
url:  "OpLogin.php",
type: "POST",
data: {"Login" : Login, "Pass" : Pass, "Assistance" : Assistance},
success: function (result) {
if(result == 0){	
$('#FormLoading').modal('hide');	
$('#ErrorLogin').show();
} else {
location.href = 'index.php'	
}}});
return false;
})})
</script>