<?php
$idRepository 		= $_GET["idRepository"];
$idUser 			= $_SESSION['idUser'];
$Query 		= ("SELECT * FROM repositories WHERE RepositoryUser = '$idUser' AND idRepository = '$idRepository'");
$Result 	= mysqli_query($mysqli, $Query);
while ($row = $Result->fetch_assoc()) {
$RepositoryName = $row["RepositoryName"];	
$RepositoryCod	= $row["CodRepository"];
	
$CreateRepository = "CREATE TABLE IF NOT EXISTS $RepositoryCod(
   id INT NOT NULL AUTO_INCREMENT,
   idUser INT NOT NULL,
   idRepository INT NOT NULL,
   Status VARCHAR(10) NOT NULL,
   SeqName TEXT NOT NULL,
   Seq TEXT NOT NULL,
   Description TEXT NULL,
   Organism TEXT NULL,
   Hits TEXT NULL,
   eValue TEXT NULL,
   Accession TEXT NULL,
   GONames TEXT NULL,
   GOFunctions TEXT NULL,
   Date DATETIME,
   PRIMARY KEY ( id )
);";
mysqli_query($mysqli, $CreateRepository) or die (mysql_error());	
	
	
}
$Search 	= mysqli_query($mysqli, "SELECT * FROM repodata WHERE idRepository = '$idRepository' and idUser = '$idUser'");
$num_rows 	= mysqli_num_rows($Search);
if(!$num_rows > 0){
$Sqli	=	("INSERT INTO `repodata` (`idUser`, `idRepository`, `Sequences`, `Status`, `Blasted`, `Result`, `Annotation`, `NoResult`) VALUES ('$idUser', '$idRepository', '--', '--', '--', '--', '--', '--')");
mysqli_query($mysqli, $Sqli);
}
?>
<div class="text-center text-white h3 mt-5 mb-5">Upload to repository <b><i><?php echo($RepositoryName);?></i></b></div>
<div class="text-center text-white h3 mt-5 mb-5">Upload *.fasta, *.fas or *.fa File</div>


<form class="w-75 mx-auto" id="uploadForm" enctype="multipart/form-data">
<div class="input-group mb-3">
<input type="file" class="form-control form-control-lg" name="file" id="fileInput" accept=".fasta">
<input name="idRepository" type="hidden" id="idRepository" value="<?php echo($idRepository);?>">
<input name="idUser" type="hidden" id="idUser" value="<?php echo($idUser);?>">
<input name="RepositoryCod" type="hidden" id="RepositoryCod" value="<?php echo($RepositoryCod);?>">
<button class="btn btn-lg btn-success" type="submit" value="Submit"><i class="fas fa-upload"></i> Upload</button>
</div>	
</form>

<div id="Loading">

<div id="Uploading" class="text-center h2 text-white">Uploading and Processing file, please wait...</div>
	
	
<div class="mx-auto text-center" id="uploadStatus"><div class="loadingio-spinner-pulse-4mkc02jc44n"><div class="ldio-yo4jhc4idir">
<div></div><div></div><div></div>
</div></div>
<style type="text/css">
@keyframes ldio-yo4jhc4idir-1 {
  0% { top: 36px; height: 128px }
  50% { top: 60px; height: 80px }
  100% { top: 60px; height: 80px }
}
@keyframes ldio-yo4jhc4idir-2 {
  0% { top: 41.99999999999999px; height: 116.00000000000001px }
  50% { top: 60px; height: 80px }
  100% { top: 60px; height: 80px }
}
@keyframes ldio-yo4jhc4idir-3 {
  0% { top: 48px; height: 104px }
  50% { top: 60px; height: 80px }
  100% { top: 60px; height: 80px }
}
.ldio-yo4jhc4idir div { position: absolute; width: 30px }.ldio-yo4jhc4idir div:nth-child(1) {
  left: 35px;
  background: #ffffff;
  animation: ldio-yo4jhc4idir-1 1s cubic-bezier(0,0.5,0.5,1) infinite;
  animation-delay: -0.2s
}
.ldio-yo4jhc4idir div:nth-child(2) {
  left: 85px;
  background: #ffffff;
  animation: ldio-yo4jhc4idir-2 1s cubic-bezier(0,0.5,0.5,1) infinite;
  animation-delay: -0.1s
}
.ldio-yo4jhc4idir div:nth-child(3) {
  left: 135px;
  background: #ffffff;
  animation: ldio-yo4jhc4idir-3 1s cubic-bezier(0,0.5,0.5,1) infinite;
  animation-delay: undefineds
}

.loadingio-spinner-pulse-4mkc02jc44n {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-yo4jhc4idir {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-yo4jhc4idir div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style></div>	

	
<div class="progress w-75 mx-auto" style="height: 25px;">
	<div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuemin="0" aria-valuemax="100"></div></div>	

<div id="uploadStatus"></div>
</div>


<script>
$(document).ready(function(){
$("#Loading").hide();
$("#Uploading").hide();
$("#uploadForm").on('submit', function(e){
e.preventDefault();
$.ajax({
xhr: function() {
var xhr = new window.XMLHttpRequest();
xhr.upload.addEventListener("progress", function(evt) {
if (evt.lengthComputable) {
var percentComplete = ((evt.loaded / evt.total) * 100);
$(".progress-bar").width(percentComplete.toFixed(2) + '%');
$(".progress-bar").html(percentComplete.toFixed(2)+ '%');
}
}, false);
return xhr;
},
			
type: 'POST',
url: 'upload.php',
data: new FormData(this),
contentType: false,
cache: false,
processData:false,
beforeSend: function(){
$("#Loading").show();
$("#Uploading").show();
$(".progress-bar").width('0%');
},
error:function(){
$('#uploadStatus').html('<p class="text-center h3" style="color:#EA4335;">File upload failed, please try again.</p>');
},
	
success: function(resp){
console.log(resp);
if(resp == 'ok'){
$('#uploadForm')[0].reset();
$('#uploadStatus').html('<p class="text-center h3" style="color:#28A74B;">File has uploaded and processed successfully!</p><p class="text-center h3 mt-3" style="color:#28A74B;">Loading Sequences Page, please wait...</p>');
setTimeout(function() {
window.location="index.php?p=ListSequences&idRepository=<?php echo($idRepository)?>"
}, 3000);

} else if (resp == 'err') {
$('#uploadStatus').html('<p class="text-center h3" style="color:#EA4335;">Please select a valid fasta file to upload.</p>');
}

}});});
});
</script>